from pathlib import Path
import shutil
import re

ROOT = Path(__file__).parent
NOTEBOOKS_DIR = ROOT / 'notebooks'
TEMPLATE_DIR = ROOT / 'template'

shutil.rmtree(NOTEBOOKS_DIR, ignore_errors = True)
NOTEBOOKS_DIR.mkdir()

(NOTEBOOKS_DIR / 'DO_NOT_MODIFY').write_text('DO NOT MODIFY ANYTHING IN THIS DIRECTORY\nIT IS GENERATED BY make.py\n')

for base_image in (ROOT / 'BASE_IMAGES.txt').read_text().splitlines():
    repo, image, tag = re.match(r'(.*)\/(.*):(.*)', base_image).groups()

    our_image = 'htc-{}'.format(image)

    image_dir = NOTEBOOKS_DIR / our_image
    shutil.copytree(TEMPLATE_DIR, image_dir, ignore = lambda *_: ['Dockerfile'])

    df = image_dir / 'Dockerfile'
    df_template = (TEMPLATE_DIR / 'Dockerfile').read_text()
    df_text = df_template.replace('<BASE_IMAGE>', base_image)
    df.write_text(df_text)
